# Problem: [289. 生命游戏](https://leetcode.cn/problems/game-of-life/description/)

## 思路

这题的可能比较麻烦的是要求原地算法的同时，要求同步更新，要避免混叠造成的异步更新。

我的想法是先建立一个大小相同的count矩阵，遍历一次原来的矩阵，让count矩阵记录每一个位置周围存活细胞的数量，然后根据count矩阵按要求更新。

这里面的另一个麻烦的点就在于边界的处理，对于边、顶点上的这些位置要单独处理。

In [3]:
class Solution:
    def gameOfLife(self, board: list[list[int]]) -> None:
        """
        Do not return anything, modify board in-place instead.
        """
        m=len(board)
        n=len(board[0])
        count=[[0 for _ in range(n)] for _ in range (m)]
        for i in range(m):
            for j in range(n):
                if board[i][j]==1:
                    left=(i-1>=0)
                    right=(i+1<m)
                    up=(j-1>=0)
                    down=(j+1<n)
                    # print(i,j,left,right,up,down)
                    if left:
                        count[i-1][j]+=1
                        if up:
                            count[i-1][j-1]+=1
                        if down:
                            count[i-1][j+1]+=1
                    if right:
                        count[i+1][j]+=1
                        if up:
                            count[i+1][j-1]+=1
                        if down:
                            count[i+1][j+1]+=1
                    if up:
                        count[i][j-1]+=1
                    if down:
                        count[i][j+1]+=1
        for i in range(m):
            for j in range(n):
                if board[i][j]==1:
                    if count[i][j]<2 or count[i][j]>3:
                        board[i][j]=0
                if board[i][j]==0:
                    if count[i][j]==3:
                        board[i][j]=1
        # return count

In [4]:
# 明明numpy很好用为什么被leetcode排挤呢？这里为了更形象的展示矩阵，使用numpy渲染测试结果
import numpy as np
test = Solution()
test1 = [[0,1,0],[0,0,1],[1,1,1],[0,0,0]]
print('第一个测试用例为:')
print(np.array(test1))
test.gameOfLife(test1)
print('测试结果为:')
print(np.array(test1))

print()

test2 = [[1,1],[1,0]]
print('第二个测试用例为:')
print(np.array(test2))
test.gameOfLife(test2)
print('测试结果为:')
print(np.array(test2))

第一个测试用例为:
[[0 1 0]
 [0 0 1]
 [1 1 1]
 [0 0 0]]
测试结果为:
[[0 0 0]
 [1 0 1]
 [0 1 1]
 [0 1 0]]

第二个测试用例为:
[[1 1]
 [1 0]]
测试结果为:
[[1 1]
 [1 1]]
