# Problem: [54. 螺旋矩阵](https://leetcode.cn/problems/spiral-matrix/description/)

## 思路：

这就是当遇到已经读过的位置或者范围以外的位置的时候，就旋转迭代方向。

考虑利用python的虚数类型自动实现迭代模式旋转
```python3 []
orient*=-1j
```

In [3]:
class Solution(object):
    def spiralOrder(self, matrix):
        """
        :type matrix: List[List[int]]
        :rtype: List[int]
        """
        m=len(matrix)
        n=len(matrix[0])
        have_read=[[False for _ in range(n)] for _ in range (m)]
        orient=1j
        # print(m,n)
        i=0
        j=0
        ans=[]
        while(len(ans)<m*n):
            # print(i,j)
            # print(orient)
            
            ans.append(matrix[i][j])
            have_read[i][j]=True
            i_next=i+int(orient.real)
            j_next=j+int(orient.imag)
            # print(i_next,j_next)
            # print()
            if  not(0<=i_next<m and 0<=j_next<n) or have_read[i_next][j_next]:
                orient*=-1j
                i+=int(orient.real)
                j+=int(orient.imag)
            else:
                i=i_next
                j=j_next
        return ans

In [4]:
# 明明numpy很好用为什么被leetcode排挤呢？这里为了更形象的展示矩阵，使用numpy渲染测试结果
import numpy as np
test = Solution()
test1 = [[1,2,3],[4,5,6],[7,8,9]]
print('第一个测试用例为:')
print(np.array(test1))
ans1=test.spiralOrder(test1)
print('测试结果为:')
print(np.array(ans1))

print()
test2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print('第二个测试用例为:')
print(np.array(test2))
ans2=test.spiralOrder(test2)
print('测试结果为:')
print(np.array(ans2))

第一个测试用例为:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
测试结果为:
[1 2 3 6 9 8 7 4 5]

第二个测试用例为:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
测试结果为:
[ 1  2  3  4  8 12 11 10  9  5  6  7]
