# Problem: [59. 螺旋矩阵 II](https://leetcode.cn/problems/spiral-matrix-ii/description/)

## 思路：

实际上是复用[这一题](https://leetcode.cn/problems/spiral-matrix/description/)的思路

当遇到已经读过的位置或者范围以外的位置的时候，就旋转迭代方向。

考虑利用python的虚数类型自动实现迭代模式旋转
```python3 []
orient*=-1j
```

In [1]:
class Solution:
    def generateMatrix(self, n: int) -> list[list[int]]:
        have_read=[[False for _ in range(n)] for _ in range (n)]
        ans=[[0 for _ in range(n)] for _ in range (n)]
        orient=1j
        # print(m,n)
        i=0
        j=0
        value=1
        while(value<=n**2):
            
            # print(i,j)
            # print(orient)
            # print(value)
            ans[i][j]=value
            value+=1
            have_read[i][j]=True
            i_next=i+int(orient.real)
            j_next=j+int(orient.imag)
            # print(i_next,j_next)
            # print()
            if  not(0<=i_next<n and 0<=j_next<n) or have_read[i_next][j_next]:
                orient*=-1j
                i+=int(orient.real)
                j+=int(orient.imag)
            else:
                i=i_next
                j=j_next
        return ans

In [2]:
# 明明numpy很好用为什么被leetcode排挤呢？这里为了更形象的展示矩阵，使用numpy渲染测试结果
import numpy as np
test = Solution()
test1 = 3
print('第一个测试用例为:')
print(np.array(test1))
ans1=test.generateMatrix(test1)
print('测试结果为:')
print(np.array(ans1))

print()
test2 = 1
print('第二个测试用例为:')
print(np.array(test2))
ans2=test.generateMatrix(test2)
print('测试结果为:')
print(np.array(ans2))

第一个测试用例为:
3
测试结果为:
[[1 2 3]
 [8 9 4]
 [7 6 5]]

第二个测试用例为:
1
测试结果为:
[[1]]
