# Problem: [498. 对角线遍历](https://leetcode.cn/problems/diagonal-traverse/description/)

## 思路1：懒人方法

首先容易想到的就是根据 $i+j$ 的奇偶性来判断是下一个是右上角还是左下角。难点在于在边界上的处理。

如果只考虑左边界和上边界，那么很容易，哪边超出边界后，直接垂直拉回来就好了。即如果发现 $i<0$ ，就直接让 $i+1$ 回去，对 $j$ 同理。

<div align=center><img src="498_diagnoal-tranverse_lazymanway.svg" width="  "></div>

对于另外两个边的处理好像不那么容易，所以不处理了，那么这样我们遍历的区域总是一个左上的三角区域。这无妨，因为这样最终总是可以覆盖我们想要的区域的，我们只需要在遍历的时候如果是想要的有效区域就做事情，如果不是那就除了迭代什么都不做。

<div align=center><img src="498_diagnoal-tranverse_lazymanwayshortcome.svg" width="  "></div>

那到什么时候停止呢，当遍历到右下角的那个元素就可以停止了

**这个方法最终超时了，超时的示例是一个很长的单行矩阵。**

In [13]:
class Solution(object):
    def findDiagonalOrder(self, mat):
        """
        :type mat: List[List[int]]
        :rtype: List[int]
        """
        dialist=[]
        m=len(mat)
        n=len(mat[0])
        i=0
        j=0
        while(i!=m-1 or j!=n-1):
            if 0<=i<=m-1 and 0<=j<=n-1:
                # print(i,j)
                dialist.append(mat[i][j])
            if((i+j)%2):
                # print('Hlere')
                i+=1
                j-=1
            else:
                i-=1
                j+=1
            if i<0:
                i+=1
            if j<0:
                j+=1
        dialist.append(mat[i][j])
        return dialist

In [14]:
# 明明numpy很好用为什么被leetcode排挤呢？这里为了更形象的展示矩阵，使用numpy渲染测试结果
import numpy as np
test = Solution()
test1 = [[1,2,3],[4,5,6],[7,8,9]]
print('第一个测试用例为:')
print(np.array(test1))
ans1=test.findDiagonalOrder(test1)
print('测试结果为:')
print(np.array(ans1))

print()
test2 = [[1,2,3,4,5,6,7,8,9]]
print('第二个测试用例为:')
print(np.array(test2))
ans2=test.findDiagonalOrder(test2)
print('测试结果为:')
print(np.array(ans2))

第一个测试用例为:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
测试结果为:
[1 2 4 7 5 3 6 8 9]

第二个测试用例为:
[[1 2 3 4 5 6 7 8 9]]
测试结果为:
[1 2 3 4 5 6 7 8 9]


## 思路2

根据上一个思路，当超出左边界和上边界时，直接垂直拉回来就好了。上一个思路在一个很长很长的单行测试用例上超时了，原因也很简单，我们多余遍历了很多东西。

于是必须专门处理下边界和右边界的问题，其实想一想，也很简单，如图中紫色箭头所示。
- 当超出下边界，即 $i\geqslant m$ 的时候，需要将 $i$ 拉回来的同时，$j$ 自加 **2**。
- 超出有边界同理，把 $j$ 拉回来，$i$ 自加2。

<div align=center><img src="498_diagnoal-tranverse_thefullway.svg" width="  "></div>


In [15]:
class Solution(object):
    def findDiagonalOrder(self, mat):
        """
        :type mat: List[List[int]]
        :rtype: List[int]
        """
        dialist=[]
        m=len(mat)
        n=len(mat[0])
        i=0
        j=0
        while(i!=m-1 or j!=n-1):
            orient=bool((i+j)%2)
            if 0<=i<=m-1 and 0<=j<=n-1:
                # print(i,j)
                dialist.append(mat[i][j])           
                if orient:
                    i+=1
                    j-=1
                else:
                    i-=1
                    j+=1
            elif i<0 and 0<=j<=n-1:
                i+=1
            elif j<0 and 0<=i<=m-1:
                j+=1
            elif i>=m and j<=n-1:
                i-=1
                j+=2
            elif j>=n and i<=m-1:
                j-=1
                i+=2
            else:
                break
        dialist.append(mat[i][j])
        return dialist

In [16]:
# 明明numpy很好用为什么被leetcode排挤呢？这里为了更形象的展示矩阵，使用numpy渲染测试结果
import numpy as np
test = Solution()
test1 = [[1,2,3],[4,5,6],[7,8,9]]
print('第一个测试用例为:')
print(np.array(test1))
ans1=test.findDiagonalOrder(test1)
print('测试结果为:')
print(np.array(ans1))

print()
test2 = [[1,2,3,4,5,6,7,8,9]]
print('第二个测试用例为:')
print(np.array(test2))
ans2=test.findDiagonalOrder(test2)
print('测试结果为:')
print(np.array(ans2))

第一个测试用例为:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
测试结果为:
[1 2 4 7 5 3 6 8 9]

第二个测试用例为:
[[1 2 3 4 5 6 7 8 9]]
测试结果为:
[1 2 3 4 5 6 7 8 9]
