# Problem: [48. 旋转图像](https://leetcode.cn/problems/rotate-image/description/)

## 思路1

这个旋转是一种置换，可以构造出角标变换关系来做

简单探索了一下，发现旋转就是行反序加转置

$$
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}\xrightarrow{\text{行反序}}\begin{bmatrix}
7 & 8 & 9\\
4 & 5 & 6\\
1 & 2 & 3
\end{bmatrix}\xrightarrow{\text{转置}}\begin{bmatrix}
7 & 4 & 1\\
8 & 5 & 2\\
9 & 6 & 3
\end{bmatrix}
$$

所以角标变换关系就是 $(i,j)\to (m-1-i,j) \to (j,m-1-i)$

如果遍历新矩阵，那就要写成 $(n-1-j,i)\to (i,j)$ 

使用```matrix[:]=new_matrix```的方法强行变为原地算法

In [12]:
class Solution(object):
    def rotate(self, matrix):
        """
        :type matrix: List[List[int]]
        :rtype: None Do not return anything, modify matrix in-place instead.
        """
        n=len(matrix)
        mc=[[0 for _ in range(n)] for _ in range(n)]
        for i in range(n):
            for j in range(n):
                # print(matrix[n-j-1][i])
                mc[i][j]=matrix[n-j-1][i]
                # print(i,j,mc[i][j])
        # print(mc[0][0])
        # print(mc)
        matrix[:]=mc

In [13]:
# 明明numpy很好用为什么被leetcode排挤呢？这里为了更形象的展示矩阵，使用numpy渲染测试结果
import numpy as np
test = Solution()
test1 = [[1,2,3],[4,5,6],[7,8,9]]
print('第一个测试用例为:')
print(np.array(test1))
test.rotate(test1)
print('测试结果为:')
print(np.array(test1))

print()

test2 = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
print('第二个测试用例为:')
print(np.array(test2))
test.rotate(test2)
print('测试结果为:')
print(np.array(test2))

第一个测试用例为:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
测试结果为:
[[7 4 1]
 [8 5 2]
 [9 6 3]]

第二个测试用例为:
[[ 5  1  9 11]
 [ 2  4  8 10]
 [13  3  6  7]
 [15 14 12 16]]
测试结果为:
[[15 13  2  5]
 [14  3  4  1]
 [12  6  8  9]
 [16  7 10 11]]


## 思路2

查到了一个一行解决问题的代码，实际上和思路1有些联系
$$
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}\xrightarrow{\text{转置}}\begin{bmatrix}
1 & 4 & 7\\
2 & 5 & 8\\
3 & 6 & 9
\end{bmatrix}\xrightarrow{\text{列反序}}\begin{bmatrix}
7 & 4 & 1\\
8 & 5 & 2\\
9 & 6 & 3
\end{bmatrix}
$$

然后，我们有如下操作

- zip(*matrix)：这个部分使用 zip 函数将矩阵进行转置，即将矩阵的行变成列，列变成行。这样可以达到矩阵转置的效果。
- row[::-1] for row in ...：对于转置后的矩阵的每一行，使用切片 [::-1] 反转该行的元素顺序。
- matrix[:] = ...：最终将原始矩阵的内容用反转后的矩阵内容来替换。这样就完成了矩阵的顺时针旋转。

In [14]:
class Solution:
    def rotate(self, matrix: list[list[int]]) -> None:
        matrix[:] = [row[::-1] for row in zip(*matrix)]

# 作者：_G_
# 链接：https://leetcode.cn/problems/rotate-image/solutions/2489887/yuan-di-xuan-zhuan-pythonyi-xing-dai-ma-d0tez/
# 来源：力扣（LeetCode）
# 著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

In [15]:
# 明明numpy很好用为什么被leetcode排挤呢？这里为了更形象的展示矩阵，使用numpy渲染测试结果
# import numpy as np
test = Solution()
test1 = [[1,2,3],[4,5,6],[7,8,9]]
print('第一个测试用例为:')
print(np.array(test1))
test.rotate(test1)
print('测试结果为:')
print(np.array(test1))

print()

test2 = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
print('第二个测试用例为:')
print(np.array(test2))
test.rotate(test2)
print('测试结果为:')
print(np.array(test2))

第一个测试用例为:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
测试结果为:
[[7 4 1]
 [8 5 2]
 [9 6 3]]

第二个测试用例为:
[[ 5  1  9 11]
 [ 2  4  8 10]
 [13  3  6  7]
 [15 14 12 16]]
测试结果为:
[[15 13  2  5]
 [14  3  4  1]
 [12  6  8  9]
 [16  7 10 11]]
