# Problem: [73. 矩阵置零](https://leetcode.cn/problems/set-matrix-zeroes/description/)

## 思路

思路很简单，就是遍历数组，然后用set记录有0的行和列，然后只要是这些行列上的就设为0

记录完行和列后，之前想过用numpy遍历行和列进行整行整列的置零。本来向着这样快一点，但是在leetcode上允许的结果还不如不用numpy再遍历一遍数组，对每一个元素逐个判断。

In [5]:
class Solution(object):
    def setZeroes(self, matrix):
        """
        :type matrix: List[List[int]]
        :rtype: None Do not return anything, modify matrix in-place instead.
        """
        lx=len(matrix)
        ly=len(matrix[0])
        zerox,zeroy=set(),set()
        for i in range(lx):
            for j in range(ly):
                if matrix[i][j]==0:
                    zerox.add(i)
                    zeroy.add(j)
        if not zerox:
            return
        for i in range(lx):
            for j in range(ly):
                if (i in zerox)or(j in zeroy):
                    matrix[i][j]=0

In [6]:
test = Solution()
test1 = [[1,1,1],[1,0,1],[1,1,1]]
test.setZeroes(test1)
print(test1)

test2 = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]
test.setZeroes(test2)
print(test2)

[[1, 0, 1], [0, 0, 0], [1, 0, 1]]
[[0, 0, 0, 0], [0, 4, 5, 0], [0, 3, 1, 0]]


In [8]:
# 明明numpy很好用为什么被leetcode排挤呢？这里为了更形象的展示矩阵，使用numpy渲染测试结果
import numpy as np
test = Solution()
test1 = [[1,1,1],[1,0,1],[1,1,1]]
print('第一个测试用例为:')
print(np.array(test1))
test.setZeroes(test1)
print('测试结果为:')
print(np.array(test1))

print()

test2 = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]
print('第二个测试用例为:')
print(np.array(test2))
test.setZeroes(test2)
print('测试结果为:')
print(np.array(test2))

第一个测试用例为:
[[1 1 1]
 [1 0 1]
 [1 1 1]]
测试结果为:
[[1 0 1]
 [0 0 0]
 [1 0 1]]

第二个测试用例为:
[[0 1 2 0]
 [3 4 5 2]
 [1 3 1 5]]
测试结果为:
[[0 0 0 0]
 [0 4 5 0]
 [0 3 1 0]]
